airbnb:
  outputs:
    dev:
      type: snowflake
      account: urqflrq-rs54506 #Esto viene de la url que te dan cuando te registras en snowflake 
      user: dbt

      role: TRANSFORM
      private_key: "{{ env_var('SNOWFLAKE_PRIVATE_KEY') }}"
      private_key_passphrase: "{{ env_var('SNOWFLAKE_PRIVATE_KEY_PASSPHRASE') }}"

      database: AIRBNB
      schema: DEV
      threads: 1
      warehouse: COMPUTE_WH
  target: dev